### ISSUE TITLE
Enterprise distribution support

### ISSUE THREAD

**Issue by emmadavieswilcox** [Stack-in-a-box/chrome-live-watermark#30]
# Issues

- [ ] Design configuration schema – https://github.com/Stack-in-a-box/chrome-domain-watermarker/issues/31 (estimate: _30 minutes_)
- [ ] Allow exporting configuration – https://github.com/Stack-in-a-box/chrome-domain-watermarker/issues/32 (estimate: _1 hour_)
- [ ] Allow importing configuration – https://github.com/Stack-in-a-box/chrome-domain-watermarker/issues/33 (estimate: _2 hours_)
- [ ] Set-up a mechanism for testing enterprise deployment – https://github.com/Stack-in-a-box/chrome-domain-watermarker/issues/34 (estimate: _4-8 hours_)
- [ ] Update group policy to deploy default configuration –  https://github.com/Stack-in-a-box/chrome-domain-watermarker/issues/35 (estimate: _4-8 hours_)
- [ ] Write user documentation and/or tooling for configuring and deploying the extension – `// TODO ...`
- [ ] Test the new system with a small group of real users – `// TODO ...`
- [ ] Deploy the system across a real organisation and address any issues that arise – `// TODO ...`
- [ ] Consider which parts of the system merit automated testing (if any / if possible), and add both the scaffolding and test cases to support this – `// TODO ...`

# Estimate

Total estimate of tasks: _TBC_.
