### ISSUE TITLE
Update group policy to deploy default configuration

### ISSUE THREAD

**Issue by emmaffiondavies** [Stack-in-a-box/chrome-live-watermark#35]
# Overview

Once the group policy has been established to deploy Chrome to domain users (https://github.com/Stack-in-a-box/chrome-domain-watermarker/issues/34), we can configure it to also include JSON that can be used by the extension at run time to set the initial configuration of the extension (via the readonly `storage.managed` property).

# Tasks

- [ ] Write the necessary JSON for pre-configuring the extension.
- [ ] Configure the group policy to deploy the settings to users.
- [ ] Push the updated policy to the test user.
- [ ] Spike an update to the application that makes it clear what's contained in `storage.managed` to see whether it worked or not.

# Estimate

4-8 hours.

# Resources

* https://support.google.com/chrome/a/answer/7532015
* https://support.google.com/chrome/a/answer/3115278
